version: '3'
services:
  web:
    container_name: web
    image: nginx:latest
    volumes:
      - .:/code:cached
      - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    links:
      - ${PHP_HOST}
  php:
    container_name: ${PHP_HOST}
    build: .docker/php
    volumes:
      - .:/code:cached
      - .docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    environment:
      TIMEZONE: ${TIMEZONE}
    links:
      - ${DB_HOST}
    working_dir: /code
  mysql:
    container_name: ${DB_HOST}
    image: mysql:5.7
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"